### ISSUE TITLE
Notify User

### ISSUE THREAD

**Issue by Horft** [Schrotty/DoIT#11]
Als Nutzer möchte ich im laufenden Programm Benachrichtigungen über anstehende ToDos bekommen, um eingetragene ToDos nicht zu vergessen.

- Story Points: 5
- Story Points (Post-Schätzung): 
- Risiko: 6
- Priorisierung: 5

#### Abnahmekriterien
- User wird anhand der Notification Span über fällige ToDos benachrichtigt
- Änderungen der Notification Span muss berücksichtigt werden

**Comment by MartinDolac** [comment]
@smino Können wir uns mal zusammensetzen? Komme bei Swing nicht weiter. Die Table wird nicht richtig dargestellt.

**Comment by smino** [comment]
@MartinDolac Inwiefern wird die nicht richtig dargestellt=?  Was spielt die Table für ne Rolle bei der Benachrichtigung?

**Comment by smino** [comment]
@MartinDolac Vorschlag zu Güte, wie wäre es, wenn man nur eine Benachrichtigung pro ToDo bekommt? So fällt das Problem mit der Liste weg und man hat wie ich finde einen besseren Überblick, wenn man für jede Benachrichtigung ein einzelnes PopUp hat, welches man sich durchliest und wegklickt

**Comment by Horft** [comment]
@MartinDolac Wie geht es hier nun weiter? Ich möchte Fortschritt sehen!

**Comment by MartinDolac** [comment]
Setze mich Donnerstag/ Freitag wieder dran

**Comment by Horft** [comment]
@MartinDolac Denke bitte daran: Samstag ist Deadline.

**Comment by MartinDolac** [comment]
@PLA7IN schau doch mal drüber bitte https://github.com/Schrotty/DoIT/releases/tag/v1.0-notification

**Comment by PLA7IN** [comment]
ist das normal dass ich keine todo erstellen kann? bzw wie teste ich am besten die notification?

**Comment by PLA7IN** [comment]
ok whoops ich hatte versucht ein ToDo zu erstellen was ein tag vor dem Aktuellen anlief... weiß nicht ob man da vielleicht dran arbeiten sollte... 

ansonsten weiß ich jetzt nicht wie ich eine notification provoziere

**Comment by Schrotty** [comment]
Ein neues ToDo anlegen und als Startdatum den heutigen Tag wählen. Nach ca. 10 Sekunden wird dann eine Benachrichtigung angezeigt

**Comment by PLA7IN** [comment]
nope. funktioniert nicht. ich habs sogar ein zweites mal runtergeladen und installier in der vermutung ich hatte ein anderes doit aufm desktop... aber leider funktioniert es nicht auch nach dem zweiten todo nicht.

**Comment by Schrotty** [comment]
Ich schau es mir nochmal an

**Comment by Schrotty** [comment]
@PLA7IN Habs überarbeitet und jetzt sollte es ohne Probleme klappen.
Binaries: https://github.com/Schrotty/DoIT/releases/tag/v1.1-notification

**Comment by Horft** [comment]
Funktioniert, aber die Nachricht ist nur in der Kopfzeile? Bzw. keine andere Message?

**Comment by Schrotty** [comment]
In der Kopfzeile steht der Titel und darunter die Beschreibung

**Comment by PLA7IN** [comment]
Funktioniert auf jedenfall! man könnte vielleicht noch das Deadline-datum einblenden falls man benachrichtigt wird damit man weiß bis wann man noch zeit hat gerade wenn man ein benachrichtigungs-intervall eingestellt hat.

**Comment by Horft** [comment]
Überredet!

**Comment by Schrotty** [comment]
Martin hats angepasst. Kann ich dann nen PR erstellen? 🤔

**Comment by PLA7IN** [comment]
wenn intellij bei mir nicht ständig ausrastet und ich es mir erlaubt endlich es anzuschauen dann gern

**Comment by PLA7IN** [comment]
ok kannst ein PR machen

**Comment by Schrotty** [comment]
@MartinDolac Post-Schätzung bitte nachtragen
