### ISSUE TITLE
Finish ToDo

### ISSUE THREAD

**Issue by Horft** [Schrotty/DoIT#20]
Als Nutzer möchte ich ein ToDo als "Erledigt" markieren können, um das ToDo aus der Liste der aktiven in die Liste der archivierten ToDos zu verschieben.

* Story Points: 1
* Story Points (Post-Schätzung): 1
* Risiko: 2
* Priorisierung: 10

#### Abnahmekriterien
- ToDo von Prod nach Arch verschoben
- Listen aktualisiert

**Comment by Schrotty** [comment]
@Horft Bitte einmal prüfen ob das so korrekt ist.
Binaries: https://github.com/Schrotty/DoIT/releases/tag/v1.0-finishToDo

**Comment by Horft** [comment]
Genau richtig, top!
