### ISSUE TITLE
Falsches ToDo angezeigt bei Prod/Arch-Wechsel

### ISSUE THREAD

**Issue by Horft** [Schrotty/DoIT#24]
**Describe the bug**
Beim Wechsel zwischen prod und arch bleibt der aktuell ausgewählte ToDo angezeigt.

**To Reproduce**
1. Prod auswählen
2. ToDo auswählen
3. Arch auswählen
4. ToDo aus Prod bleibt angezeigt, obwohl arch ausgewählt wurde

**Expected behavior**
Beim Auswählen einer anderen Liste soll der erste ToDo der Liste angezeigt werden

**Comment by Schrotty** [comment]
@Horft Hab das gerade mal getestet und bei mir wird immer der erste Eintrag der jeweiligen Liste angezeigt.

**Comment by Horft** [comment]
Der Fehler wurde mit #28 behoben
