### ISSUE TITLE
Anzeige Auswahl Prod/Arch

### ISSUE THREAD

**Issue by Horft** [Schrotty/DoIT#31]
**Is your feature request related to a problem? Please describe.**
Es gibt momentan keine Anzeige ob Prod oder Arch ausgewählt ist.

**Describe the solution you'd like**
Button highlighten oder ähnliches wäre ein Vorschlag

**Comment by Schrotty** [comment]
@Horft Beim laden von Prod/Arch die entsprechenden Buttons deaktiviert.
Binaries: https://github.com/Schrotty/DoIT/releases/tag/v1.0-prodArch

**Comment by Horft** [comment]
Sieht gut aus!
