### ISSUE TITLE
Finish ToDo: NullPointerException, wenn kein ToDo ausgewählt

### ISSUE THREAD

**Issue by Horft** [Schrotty/DoIT#37]
**Describe the bug**
Finish ToDo ohne ausgewählten ToDo erzeugt NullPointerException.

**Expected behavior**
Wenn kein ToDo ausgewählt,  soll der Button keine Auswirkungen haben.

**Comment by Schrotty** [comment]
@Horft oder @PLA7IN Bitte einmal absegnen.
Binaries: https://github.com/Schrotty/DoIT/releases/tag/v1.0-finish-fix

**Comment by Horft** [comment]
Nun ist es so, dass bei delete per Hand ein ToDo ausgewählt werden muss, bei finish das gerade angezeigte ToDo aber in die Arch-Liste geschoben wird.

Da sollte der PO @PLA7IN mal entscheiden in welche Richtung es gehen soll.

**Comment by Horft** [comment]
Aus Sicht der QA wäre es sicherer erst ein ToDo auswählen zu müssen, um es zu finishen/deleten (DAUs und so... ;) )

**Comment by PLA7IN** [comment]
Klingt für mich logisch. Wie währ es denn sonnst händelbar? ansonsten hab ich ein problem überhaupt etwas zu erkennen (siehe anhang).
![doit](https://user-images.githubusercontent.com/29918359/41408922-b3a6c8a4-6fd4-11e8-9c3f-655f552626a8.PNG)

**Comment by Schrotty** [comment]
Dann müssten wir aber die Bedinung insgesamt umbauen. Es wird ja nachem finishen einer Aufgabe automatisch das oberste in der Liste ausgewählt/ angezeigt.

**Comment by Horft** [comment]
Meiner Meinung nach sollte das oberste ToDo der Liste wirklich nur angezeigt und nicht ausgewählt sein. Wir haben keine Nachfrage, ob das ToDo wirklich gelöscht/als fertig markiert werden soll, von daher muss es irgendeine andere Absicherung diesbezüglich geben.

**Comment by Horft** [comment]
Sieht gut aus.

**Comment by Horft** [comment]
Versuch mal den Vollbildmodus, ist leider sehr bescheiden gemacht, dass man das Fenster nicht sinnvoll kleiner machen kann.

**Comment by PLA7IN** [comment]
Das muss doch besser gehen...
![doit2](https://user-images.githubusercontent.com/29918359/41464025-f7886cac-7098-11e8-9693-d44b512611d7.PNG)

**Comment by Schrotty** [comment]
@PLA7IN Ja, dann aber bitte in nem anderen Ticket. Würde das hier gerne mergen, dann kann @smino auch seins fertigstellen ohne das ihm Exceptions um die Ohren fliegen. @Horft findet es ja so gut und als Ex-PO sollte das als Abnahme doch durchgehen, oder?

**Comment by PLA7IN** [comment]
dann kann ich leider zu den buttons z.Z. kein statement abgeben da wie man sieht ich nichts sehen kann und auch nicht mit diesen arbeiten kann
