### ISSUE TITLE
View Milestones

### ISSUE THREAD

**Issue by Horft** [Schrotty/DoIT#6]
Angelegte Milestones können mit ihrem gesamten Inhalt angezeigt werden

Als Nutzer möchte ich mir einen Milestone anzeigen lassen können, um den Inhalt betrachten zu können.

- Story Points: 3
- Story Points (Post-Schätzung): 
- Risiko: 2
- Priorisierung: 7 

#### Abnahmekriterien
- Daten des Milestones werden angezeigt
- ToDos des Milestones werden in der Liste der ToDos angezeigt

**Comment by PLA7IN** [comment]
waiting for GUI-modification

**Comment by smino** [comment]
@PLA7IN Ich kann auf diesen Branch leider nichts Pushen, Versuche es noch hinzuebkommen, ansonsten müsste du bitte die Änderungen bei dir lokal ändern, Ich kann dir die Code Änderungen geben oder du schaust selbst einmal.

**Comment by PLA7IN** [comment]
ja ok können wir auch so machen

**Comment by PLA7IN** [comment]
achso text nur halb gelesen...
@smino währ gut wenn du mir die codeänderung geben könntest wenn du die schon erstellt hast. ansonsten müsst ich mich erst in den gui code einlesen was auch möglich ist aber ein wenig braucht.

**Comment by Schrotty** [comment]
@PLA7IN @smino Wie schaut es hier aus? Von dem Ticket sind noch zwei weitere Abhängig und heute ist der letzte Tag an dem noch Änderungen angenommen werden.
Wenn irgendwer Probleme hat, soll er sich melden, damit die aus der Welt geschafft werden können.
