### ISSUE TITLE
Priorisierung der ToDos

### ISSUE THREAD

**Issue by Horft** [Schrotty/DoIT#7]
Als Nutzer möchte ich ToDos eine Priorisierung zuordnen können, sodass ich durch farbliche Kennzeichnung schnell überblicken kann welche ToDos wichtig für mich sind.

- Story Points: 5
- Story Points (Post-Schätzung): 
- Risiko: 9
- Priorisierung: 8

Info: Bitte ins Lastenheft einfügen!

**Comment by Schrotty** [comment]
Wollte gerade die Swing Forms mit IntelliJ bearbeiten, allerdings sind die allesamt leer. Wie bearbeitest du die denn? @smino

**Comment by Schrotty** [comment]
Bitte einmal drüberschauen. @MartinDolac 
Binaries: https://github.com/Schrotty/DoIT/releases/tag/v1.0-taskPrio

**Comment by MartinDolac** [comment]
Sieht gut aus!
