### ISSUE TITLE
Modify ToDo

### ISSUE THREAD

**Issue by Horft** [Schrotty/DoIT#8]
Als Nutzer möchte ich einen bereits angelegten ToDo bearbeiten können, um Änderungen einpflegen zu können.

- Story Points: 3
- Story Points (Post-Schätzung): 
- Risiko: 3
- Priorisierung: 6

#### Abnahmekriterien
- Alle Daten des zu bearbeitenden ToDos werden angezeigt
- Alle möglichen Eingaben sind veränderbar
- Änderungen des ToDos nach Bestätigung gespeichert

### Dependencies:
#7 (Priorisierung von ToDos)

**Comment by smino** [comment]
Aufgrund noch fehlender implementierung von Milestone und Priority bleibt dieses Issue vorerst noch in Progress

**Comment by smino** [comment]
@Horft Bitte einmal aufnehmen

**Comment by smino** [comment]
@Schrotty du als 2ter Developer, magst du mal rüber schauen? Nullpointer Exception, gleiches Problem wie bei finish, bei auswahl keines ToDo's kommt ne Exception

**Comment by Schrotty** [comment]
@smino Das wird mit #37 behoben.

**Comment by smino** [comment]
@Schrotty also kann das selbst mit exception gemerget werden?

**Comment by smino** [comment]
Folgendes, Edit ToDo ist soweit fertig, bis auf eine Kleinigkeit, die ich in zusammenarbeit mit @Schrotty bisher nicht lösen konnte, wenn man Editiert und dieses ToDo einem Milestone zugewiesen wurde, wird im Edit Modus  immer der letzte Milestone in der Liste angezeigt. Leider konnten wir dieses Problem nichtmehr rechtzeitig fixen.

**Comment by Schrotty** [comment]
@smino Bitte Post-Schätzung nachtragen
